development:
  video_url:
    V03: 'videos/03_low.mp4'
    V03a: 'videos/03a_low.mp4'
    V03b: 'videos/03b_low.mp4'
    V06: 'videos/06_low.mp4'
    V06a: 'videos/06a_low.mp4'
    V06b: 'videos/06b_low.mp4'
    V06c: 'videos/06c_low.mp4'
  question:
    Q03: 'Was soll ich machen?'
    Q06: 'Was wäre sinnvoll?'
  answer:
    A03a: 'A: Milch holen'
    A03b: 'B: Nichts tun'
    A06a: 'A: Neue Batterien in die Hörgeräte einsetzen'
    A06b: 'B: Badezimmerschlüssel sichern'
    A06c: 'C: Nackt tanzen'

production:
  video_url:
    V03: "https://owncloud.hpi.de/public.php?service=files&t=d039b24415d22e191b6861abdad69ff8&download"
    V03a: "https://owncloud.hpi.de/public.php?service=files&t=656deaceb5973b366e3a912fd74dab75&download"
    V03b: "https://owncloud.hpi.de/public.php?service=files&t=5c32d5a4b51637021bd363f870553a7a&download"
