development: &common_settings
  video:
    v1: &v1_config
      url: 'videos/iamerror_100_0.mp4'
      question: 'Was soll ich machen?'
      answers:
        a: 'Nichts tun'
        b: 'Milch holen'
      sequels:
        a: 'v2a'
        b: 'v2b'
    v2a: &v2a_config
      url: 'videos/iamerror_200_A.mp4'
      question: 'Was wäre sinnvoll?'
      answers:
        a: 'Neue Batterien in die Hörgeräte einsetzen'
        b: 'Badezimmerschlüssel sichern'
        c: 'Nackt tanzen'
      sequels:
        a: 'v3a'
        b: 'v3b'
        c: 'v3c'
    v2b:
      <<: *v2a_config
      url: 'videos/iamerror_200_B.mp4'
    v3a: &v3a_config
      url: 'videos/iamerror_300_A.mp4'
      question: 'Was nun?'
      answers:
        a: 'Aufstehen und weitermachen'
        b: 'Aufgeben'
      sequels:
        a: 'v4a'
        b: 'v4b'
    v3b:
      <<: *v3a_config
      url: 'videos/iamerror_300_B.mp4'
    v3c:
      <<: *v3a_config
      url: 'videos/iamerror_300_C.mp4'
    v4a:
      url: 'videos/iamerror_400_A.mp4'
      # question: 'Was nun?'
      # answers:
      #   a: 'Aufstehen und weitermachen'
      #   b: 'Aufgeben'
      # sequels:
      #   a: 'v4a'
      #   b: 'v4b'
    v4b:
      url: 'videos/iamerror_400_B.mp4'
    #TODO ADD all videos here


production:
  <<: *common_settings
  video:
    v1:
      <<: *v1_config
      url: "https://owncloud.hpi.de/public.php?service=files&t=fecc1ce6582127194e8ff94fd5620558&download"
    v2a:
      <<: *v2a_config
      url: "https://owncloud.hpi.de/public.php?service=files&t=fb8110a95c9510dd104de410809dd80e&download"
    v2b:
      <<: *v2a_config
      url: "https://owncloud.hpi.de/public.php?service=files&t=b1aed6d56bc1589ad4e223058d080ad5&download"
    v3a:
      <<: *v3a_config
      url: "https://owncloud.hpi.de/public.php?service=files&t=7441e49bff306e1a712ff4940b841762&download"
    v3b:
      <<: *v3a_config
      url: "https://owncloud.hpi.de/public.php?service=files&t=ba8ac2ed67081ccccd3c894925a7c41b&download"
    v3c:
      <<: *v3a_config
      url: "https://owncloud.hpi.de/public.php?service=files&t=dad2a584113e076cca514bf9a0bce53e&download"
    v4a:
      url: "https://owncloud.hpi.de/public.php?service=files&t=542c55aef548b6f6665118c1bdd693e5&download"
    v4b:
      url: "https://owncloud.hpi.de/public.php?service=files&t=e57f19110bdfb64be12385ca6b09d100&download"
