remote_url: 'https://owncloud.hpi.de/public.php?service=files&t=871d402ab8391ade2095fe728b15779b&path=%2F&files='
video:
  v1:
    file: 'iamerror_01.mp4'
    question: 'Wer soll Milch kaufen?'
    answers:
      a: 'Hanna'
      b: 'Sebastian'
    sequels:
      a: 'v2'
      b: 'v3'
  v2: &v2_config
    file: 'iamerror_02.mp4'
    question: 'Was soll Hanna tun?'
    answers:
      a: 'Aufstehen'
      b: 'Aufgeben'
    sequels:
      a: 'v4'
      b: 'v7'
  v3:
    <<: *v2_config
    file: 'iamerror_03.mp4'
  v4:
    <<: *v2_config
    file: 'iamerror_04.mp4'
    sequels:
      a: 'v5'
      b: 'v7'
  v5:
    <<: *v2_config
    file: 'iamerror_05.mp4'
    sequels:
      a: 'v6'
      b: 'v7'
  v6: &v6_config
    file: 'iamerror_06.mp4'
    question: 'Mit wem sprechen?'
    answers:
      a: 'Elias'
      b: 'Papa'
    sequels:
      a: 'v8'
      b: 'v9'
  v7:
    <<: *v6_config
    file: 'iamerror_07.mp4'
    sequels:
      a: 'v10'
      b: 'v11'
  v8: &v8_config
    file: 'iamerror_08.mp4'
    question: 'Sebastian zur Rede stellen?'
    answers:
      a: 'Ja'
      b: 'Nein'
    sequels:
      a: 'v12'
      b: 'v13'
  v9:
    <<: *v8_config
    file: 'iamerror_09.mp4'
  v10:
    <<: *v8_config
    file: 'iamerror_10.mp4'
  v11:
    <<: *v8_config
    file: 'iamerror_11.mp4'
  v12: &v12_config
    file: 'iamerror_12.mp4'
    question: 'Was willst du Hanna schreiben?'
    answers:
      a: 'Hanna selbst herausfinden lassen wie es weitergeht'
      b: 'Hanna schreiben: Umleitung über Hansaweg!'
      c: 'Hanna schreiben: Umleitung übers Ostufer!' # Hansagasse
    sequels:
      a: 'v14'
      b: 'v15'
      c: 'v16'
  v13:
    <<: *v12_config
    file: 'iamerror_13.mp4'
  v14: &v14_config
    file: 'iamerror_14.mp4'
    question: 'Dein Schnürsenkel ist offen!'
    answers:
      a: 'SENDEN'
      b: 'LÖSCHEN'
    sequels:
      a: 'v17'
      b: 'v18'
  v15:
    <<: *v14_config
    file: 'iamerror_15.mp4'
  v16:
    <<: *v14_config
    file: 'iamerror_16.mp4'
  v17: &v17_config
    file: 'iamerror_17.mp4'
    question: 'Mit wem soll ich sprechen?'
    answers:
      a: 'Vivi'
      b: 'Sebastian'
    sequels:
      a: 'v19'
      b: 'v20'
  v18:
    <<: *v17_config
    file: 'iamerror_18.mp4'
    sequels:
      a: 'v21'
      b: 'v22'
  v19: &v19_config
    file: 'iamerror_19.mp4'
    question: 'Was soll ich mit dem Handy machen?'
    answers:
      a: 'Handy abgeben'
      b: 'Handy behalten'
    sequels:
      a: 'v23'
      b: 'v24'
  v20:
    <<: *v19_config
    file: 'iamerror_20.mp4'
  v21: &v21_config
    <<: *v19_config
    file: 'iamerror_21.mp4'
    sequels:
      a: 'v25'
      b: 'v26'
  v22:
    <<: *v21_config
    file: 'iamerror_22.mp4'
  v23:
    file: 'iamerror_23.mp4' # Ende 1
  v24: &v24_config
    file: 'iamerror_24.mp4'
    question: 'Schreib Hanna:'
    answers:
      a: 'Na, etwas schwindelig?'
      b: 'Versteck dich!'
    sequels:
      a: 'v27'
      b: 'v28'
  v25:
    file: 'iamerror_25.mp4' # Ende 1
  v26:
    <<: *v24_config
    file: 'iamerror_26.mp4'
  v27: &v27_config
    file: 'iamerror_27.mp4'
    question: 'Hast du was mit der Explosion zu tun?'
    answers:
      a: 'Ich weiß was! ;)'
      b: 'Ich war da.'
      c: "Ich war's! ;)"
    sequels:
      a: 'v29'
      b: 'v30'
      c: 'v31'
  v28:
    <<: *v27_config
    file: 'iamerror_28.mp4'
  v29:
    file: 'iamerror_29.mp4'
    question: 'Was weißt du denn?'
    answers:
      a: 'Du verlierst den Verstand!'
      b: 'Der Täter verfolgt dich!'
    sequels:
      a: 'v33'
      b: 'v32'
  v30: &v30_config
    file: 'iamerror_30.mp4'
    question: 'Weißt du wer der Täter ist?'
    answers:
      a: 'Elias'
      b: 'Hanna'
      c: 'Vivi'
      d: 'Sebastian'
    sequels:
      a: 'v36' # Ende 2
      b: 'v37' # Ende 2
      c: 'v35' # Ende 2
      d: 'v34' # Ende 2
  v31:
    <<: *v30_config
    file: 'iamerror_31.mp4'
    question: 'Wer bist du?'
  v32:
    <<: *v30_config
    file: 'iamerror_32.mp4'
    question: 'Weißt du wer der Täter ist?'
  v33:
    file: 'iamerror_33.mp4'
    question: '???'
    answers:
      a: 'Hör genau hin!'
      b: 'Hol dir Hilfe!'
    sequels:
      a: 'v37' # Ende 2
      b: 'v37' # Ende 2
  v34:
    file: 'iamerror_34.mp4'
  v35:
    file: 'iamerror_35.mp4'
  v36:
    file: 'iamerror_36.mp4'
  v37:
    file: 'iamerror_37.mp4'
